### ISSUE TITLE
refine false & experiment.h5 in folder

### ISSUE THREAD

**Issue by k-eks** [YellProgram/Yell#14]
I was running yell with the iron example (as-is) in a folder, where an unrelated experiment.h5 file was present. Yell throwed an error because file and model data was not the same. Should Yell really check the experiment.h5 when it is not supposed to refine? 

Input file read, performing a test calculation...
Parsing is ok.
Scattering is calculated in 6 sec.
Unit cell: 3.581 3.581 3.581 90 90 90 
Reciprocal unit cell: 0.279252 0.279252 0.279252 90 90 90 
Laue symmetry: m-3m
Diffuse scattering array size: 200 200 200
Diffuse scattering grid limits: -10 9.9, -10 9.9, -10 9.9, 
Grid step sizes: 0.1 0.1 0.1
Grid limits in PDF space: -5 4.95, -5 4.95, -5 4.95, 
Grid step sizes in PDF space: 0.05 0.05 0.05
Calculation method: direct
Number of refined parameters: 10

 ERROR: Dataset experiment.h5 has incorrect size (201 201 201)  expected (200 200 200)

libc++abi.dylib: terminating
Abort trap: 6

**Comment by aglie** [comment]
In case when experiment and model have different size this means they cannot be compared. Most frequently this means that during exporting the experiment something went wrong. I found this error message very helpful.

**Comment by k-eks** [comment]
Indeed, it is helpful! I just happened to have an unrelated experiment.h5 in the same folder and told Yell explicitly to not do a refinement because I knew that the definitions in the model.txt weren't matching the h5 file.

**Comment by aglie** [comment]
Then I will keep it as-is ))
