### ISSUE TITLE
Example model.txt

### ISSUE THREAD

**Issue by rayosborn** [YellProgram/Yell#4]
Is it possible to provide an example model.txt that should work? I have downloaded the Mac version of the program, but I would like to make sure it's working before generating my own model.

**Comment by aglie** [comment]
Yes, sure. The simple one is provided in the Examples section:

The [iron-void example](https://www.crystal.mat.ethz.ch/people/phd_stud/asimonov/iron-void_example.zip). 
Scripts for visualizing 3D-∆PDF: [python](https://www.crystal.mat.ethz.ch/people/phd_stud/asimonov/Visualize_yell_python.zip), [Matlab](https://www.crystal.mat.ethz.ch/people/phd_stud/asimonov/visualization_scripts_for_matlab.zip).

Also, the preparation of the diffuse scattering for Yell is covered relatively briefly in the manual. I now have the beta pre-release version of the program for reciprocal space reconstruction. So if you have any problems at this initial step do not hesitate to contact me, I will be more than happy to help with the data preparation.

**Comment by rayosborn** [comment]
I found I already had that file - sorry I missed that. 

I wonder whether you have thought about storing the results in a NeXus-formatted HDF5 file. There is a convenient Python API that would make it easy to write a Python wrapper to Yell that would place all the output arrays (as well as the input arrays) in a single HDF5 file. They could then be viewed in a generic NeXus viewer, such as NeXpy (http://nexpy.github.io/nexpy/). I was able to view all your data files in NeXpy, and run an animation of slices in all three dimensions.

**Comment by aglie** [comment]
Well, I have never heard of the NeXus. I will take a look at it and make a python converter then as a first step.

**Comment by rayosborn** [comment]
The underlying NeXus API is available separately as the nexusformat package (`pip install nexusformat`)  so you don't have to install the full NeXpy program for use in Yell (although I think it could be useful for visualization). 

Here is a Python script that creates a single valid NeXus file with all the HDF5 arrays:

    from nexusformat.nexus import *

    average = nxload('average.h5').data
    delta_pdf = nxload('delta-pdf.h5').data
    full = nxload('full.h5').data
    model = nxload('model.h5').data

    Qh = NXfield(np.linspace(-10.0, 10.0, 201), name='Qh')
    Qk = NXfield(np.linspace(-10.0, 10.0, 201), name='Qk')
    Ql = NXfield(np.linspace(-10.0, 10.0, 201), name='Ql')

    entry = NXentry()
    entry.average = NXdata(average, (Ql, Qk, Qh))
    entry.delta_pdf = NXdata(delta_pdf, (Ql, Qk, Qh))
    entry.full = NXdata(full, (Ql, Qk, Qh))
    entry.model = NXdata(model, (Ql, Qk, Qh))

    entry.save('yell.nxs')

The resulting file has the following tree structure:

  entry:NXentry
    average:NXdata
      @axes = Ql:Qk:Qh
      @signal = data
      Qh = [-10.   -9.9  -9.8 ...,   9.8   9.9  10. ]
      Qk = [-10.   -9.9  -9.8 ...,   9.8   9.9  10. ]
      Ql = [-10.   -9.9  -9.8 ...,   9.8   9.9  10. ]
      data = float64(200x200x200)
    delta_pdf:NXdata
      @axes = Ql:Qk:Qh
      @signal = data
      Qh = [-10.   -9.9  -9.8 ...,   9.8   9.9  10. ]
      Qk = [-10.   -9.9  -9.8 ...,   9.8   9.9  10. ]
      Ql = [-10.   -9.9  -9.8 ...,   9.8   9.9  10. ]
      data = float64(200x200x200)
    full:NXdata
      @axes = Ql:Qk:Qh
      @signal = data
      Qh = [-10.   -9.9  -9.8 ...,   9.8   9.9  10. ]
      Qk = [-10.   -9.9  -9.8 ...,   9.8   9.9  10. ]
      Ql = [-10.   -9.9  -9.8 ...,   9.8   9.9  10. ]
      data = float64(200x200x200)
    model:NXdata
      @axes = Ql:Qk:Qh
      @signal = data
      Qh = [-10.   -9.9  -9.8 ...,   9.8   9.9  10. ]
      Qk = [-10.   -9.9  -9.8 ...,   9.8   9.9  10. ]
      Ql = [-10.   -9.9  -9.8 ...,   9.8   9.9  10. ]
      data = float64(200x200x200)

**Comment by aglie** [comment]
Oh, looks great. Checking it already.

**Comment by aglie** [comment]
Dear Ray,

Thank you for the preparation scripts, they worked wonderfully for me, and also the NeXpy program visualizes the dataset right of the box.

I have a specific question considering the NeXus format. In our datasets the axes h k and l (noted as Qh Qk and Ql in your script) follow the basis vectors of the crystal system, meaning they are in general not orthonormal. I could not find the NeXus fields to describe the geometry of the basis vectors. The closest I could find is [NXtransformations](http://download.nexusformat.org/doc/html/classes/base_classes/NXtransformations.html#nxtransformations) which describe the geometry of the crystal setup, but those include only translations and rotations.

Do you know how to describe the geometry of the basis vectors in NeXus?

**Comment by rayosborn** [comment]
It is a shortcoming of NeXpy that we only plot rectangular grids at the moment. It is planned to allow skewed axes to be plotted, something that Matplotlib can do, but it is not yet implemented. I don't think that NeXus defines a geometry for the basis vectors themselves, although the symmetry can be defined in an NXsample group, so that could be used to determine the angle between the reciprocal lattice vectors. It isn't stored in the NXdata group, although it might be worth thinking about that. I will raise it with the NeXus committee.

It's a good question, something we've managed to avoid by only looking at orthorhombic and higher symmetry materials. We did encounter this issue with hexagonal crystals so we will be forced to add this capability to NeXpy fairly soon.

**Comment by aglie** [comment]
Thanks a lot.

I was going to change the output slightly, I think it will not be too hard to make it NeXus compatible, since I am already using hdf5 it will add just a little organizational overhead. I will do this when I have time to modify Yell.
